sudo: false

language: go

go:
  - 1.7.1

addons:
  apt:
    packages:
      - socklog
      - runit

cache:
  apt: true
  directories:
    - /home/travis/runit
    - /home/travis/perl5
    - /home/travis/gopath/bin
    - /home/travis/gopath/pkg
    - /home/travis/gopath/src/github.com/axw
    - /home/travis/gopath/src/github.com/mattn
    - /home/travis/gopath/src/github.com/pborman
    - /home/travis/gopath/src/golang.org
    - /home/travis/gopath/src/gopkg.in

services:
    - mysql

before_install:
  - export PATH="$HOME/perl5/bin:$PATH"
  - curl -L https://cpanmin.us | perl - App::cpanminus
  - cpanm --local-lib=~/perl5 local::lib && eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)
  - cpanm -nq CPAN::Meta
  - cpanm -nq File::Spec
  - cpanm -nq Narada
  - go get -v github.com/axw/gocov/gocov
  - go get -v github.com/mattn/goveralls
  - go get -v golang.org/x/tools/cmd/cover
  - go get -v github.com/go-playground/overalls

script:
  - ./build -t

after_success:
  - overalls -project=github.com/qarea/redminems
  - goveralls -coverprofile=overalls.coverprofile -service=travis-ci

